packages:
  - "packages/*"

# 解决 codemirror 版本冲突
pnpm:
  overrides:
    # @codemirror/search@6.6.0 需要特定的 @codemirror/view 版本
    '@codemirror/view': 6.29.1
    '@codemirror/search': 6.6.0
    '@codemirror/state': 6.4.1
    '@codemirror/language': 6.10.3
