// Generated by 'unplugin-auto-import'
// We define this file manually to help TypeScript understand Nuxt auto-imports
// without requiring the actual unplugin-auto-import package
import { Router, RouteLocationNormalizedLoaded } from 'vue-router';
import { Store } from 'pinia';

declare global {
  const useAsyncData: typeof import('#app')['useAsyncData']
  const useFetch: typeof import('#app')['useFetch']
  const useRoute: () => RouteLocationNormalizedLoaded
  const useRouter: () => Router
  const useState: typeof import('#app')['useState']
  const useNuxtApp: typeof import('#app')['useNuxtApp']
  const useRuntimeConfig: typeof import('#app')['useRuntimeConfig']
  const useHead: typeof import('#app')['useHead']
  const useSeoMeta: typeof import('#app')['useSeoMeta']
  
  // Vue Composition API
  const ref: typeof import('vue')['ref']
  const computed: typeof import('vue')['computed']
  const reactive: typeof import('vue')['reactive']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const onMounted: typeof import('vue')['onMounted']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const nextTick: typeof import('vue')['nextTick']
  
  // Custom API
  const useApi: typeof import('~/composables/useApi')['useApi']
  
  // Store相关
  const useAppStore: () => Store
  const useBlogStore: () => Store
  const useUserStore: () => Store
  
  // Nuxt相关
  const definePageMeta: (meta: any) => void
}

export {} 