import { Menu } from '../modules/user/entities/menu.entity';
import { Repository } from 'typeorm';
import { Logger } from '@nestjs/common';

/**
 * 初始化菜单数据
 */
export async function initMenus(menuRepository: Repository<Menu>): Promise<void> {
  const logger = new Logger('MenuInit');

  try {
    // 检查菜单表是否为空
    const count = await menuRepository.count();
    if (count > 0) {
      logger.log('菜单数据已存在，无需初始化');
      return;
    }

    logger.log('开始初始化菜单数据...');

    // 菜单数据
    const menuData = [
      {
        id: 1,
        parentId: 0,
        type: 'M',
        name: '文章管理',
        path: 'article',
        icon: 'archives',
        component: '',
        perms: '',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2022-12-04 09:13:31'),
        updateTime: new Date('2023-02-21 15:36:45'),
      },
      {
        id: 3,
        parentId: 1,
        type: 'C',
        name: '分类管理',
        path: 'category',
        icon: 'category',
        component: '/blog/category/index',
        perms: 'blog:category:list',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2022-12-04 09:22:20'),
        updateTime: new Date('2023-02-21 15:21:19'),
      },
      {
        id: 4,
        parentId: 1,
        type: 'C',
        name: '标签管理',
        path: 'tag',
        icon: 'tag',
        component: '/blog/tag/index',
        perms: 'blog:tag:list',
        hidden: 0,
        disable: false,
        orderNum: 4,
        createTime: new Date('2022-12-04 09:23:01'),
        updateTime: new Date('2023-02-21 15:21:23'),
      },
      {
        id: 5,
        parentId: 3,
        type: 'B',
        name: '添加分类',
        path: null,
        icon: null,
        component: null,
        perms: 'blog:category:add',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2022-12-04 09:30:55'),
        updateTime: null,
      },
      {
        id: 6,
        parentId: 3,
        type: 'B',
        name: '删除分类',
        path: null,
        icon: null,
        component: null,
        perms: 'blog:category:delete',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2022-12-04 09:32:15'),
        updateTime: new Date('2022-12-26 15:39:20'),
      },
      {
        id: 7,
        parentId: 3,
        type: 'B',
        name: '修改分类',
        path: null,
        icon: null,
        component: null,
        perms: 'blog:category:update',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2022-12-04 09:33:52'),
        updateTime: null,
      },
      {
        id: 8,
        parentId: 4,
        type: 'B',
        name: '添加标签',
        path: null,
        icon: null,
        component: '',
        perms: 'blog:tag:add',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2022-12-04 10:19:51'),
        updateTime: null,
      },
      {
        id: 9,
        parentId: 4,
        type: 'B',
        name: '删除标签',
        path: null,
        icon: null,
        component: null,
        perms: 'blog:tag:delete',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2022-12-04 10:20:41'),
        updateTime: null,
      },
      {
        id: 10,
        parentId: 4,
        type: 'B',
        name: '修改标签',
        path: null,
        icon: null,
        component: null,
        perms: 'blog:tag:update',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2022-12-04 10:21:32'),
        updateTime: null,
      },
      {
        id: 11,
        parentId: 0,
        type: 'M',
        name: '系统管理',
        path: 'system',
        icon: 'system',
        component: '',
        perms: '',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2022-12-06 10:58:50'),
        updateTime: new Date('2023-01-03 18:47:19'),
      },
      {
        id: 12,
        parentId: 11,
        type: 'C',
        name: '菜单管理',
        path: 'menu',
        icon: 'tree-table',
        component: '/system/menu/index',
        perms: 'system:menu:list',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2022-12-06 16:33:56'),
        updateTime: null,
      },
      {
        id: 13,
        parentId: 11,
        type: 'C',
        name: '角色管理',
        path: 'role',
        icon: 'peoples',
        component: '/system/role/index',
        perms: 'system:role:list',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2022-12-06 17:09:55'),
        updateTime: null,
      },
      {
        id: 14,
        parentId: 11,
        type: 'C',
        name: '用户管理',
        path: 'user',
        icon: 'user',
        component: '/system/user/index',
        perms: 'system:user:list',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2022-12-06 17:10:28'),
        updateTime: null,
      },
      {
        id: 15,
        parentId: 12,
        type: 'B',
        name: '添加菜单',
        path: null,
        icon: '',
        component: null,
        perms: 'system:menu:add',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2022-12-07 10:50:22'),
        updateTime: null,
      },
      {
        id: 16,
        parentId: 12,
        type: 'B',
        name: '删除菜单',
        path: null,
        icon: '',
        component: null,
        perms: 'system:menu:delete',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2022-12-07 10:50:54'),
        updateTime: null,
      },
      {
        id: 17,
        parentId: 12,
        type: 'B',
        name: '修改菜单',
        path: null,
        icon: '',
        component: null,
        perms: 'system:menu:update',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2022-12-07 10:55:21'),
        updateTime: null,
      },
      {
        id: 18,
        parentId: 13,
        type: 'B',
        name: '添加角色',
        path: null,
        icon: null,
        component: null,
        perms: 'system:role:add',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2022-12-07 10:56:24'),
        updateTime: null,
      },
      {
        id: 19,
        parentId: 13,
        type: 'B',
        name: '删除角色',
        path: null,
        icon: null,
        component: null,
        perms: 'system:role:delete',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2022-12-07 10:56:50'),
        updateTime: null,
      },
      {
        id: 20,
        parentId: 13,
        type: 'B',
        name: '修改角色',
        path: null,
        icon: null,
        component: null,
        perms: 'system:role:update',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2022-12-07 10:57:15'),
        updateTime: null,
      },
      {
        id: 21,
        parentId: 0,
        type: 'M',
        name: '日志管理',
        path: 'log',
        icon: 'log',
        component: '',
        perms: '',
        hidden: 0,
        disable: false,
        orderNum: 4,
        createTime: new Date('2022-12-21 17:36:39'),
        updateTime: new Date('2023-02-21 15:20:13'),
      },
      {
        id: 22,
        parentId: 21,
        type: 'C',
        name: '操作日志',
        path: 'operation',
        icon: 'form',
        component: '/system/log/operation',
        perms: 'log:operation:list',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2022-12-21 20:14:01'),
        updateTime: null,
      },
      {
        id: 23,
        parentId: 21,
        type: 'C',
        name: '异常日志',
        path: 'exception',
        icon: 'bug',
        component: '/system/log/exception',
        perms: 'log:exception:list',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2022-12-21 20:48:25'),
        updateTime: null,
      },
      {
        id: 24,
        parentId: 22,
        type: 'B',
        name: '删除操作日志',
        path: null,
        icon: null,
        component: null,
        perms: 'log:operation:delete',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2022-12-26 16:43:00'),
        updateTime: null,
      },
      {
        id: 25,
        parentId: 23,
        type: 'B',
        name: '删除异常日志',
        path: null,
        icon: null,
        component: null,
        perms: 'log:exception:delete',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2022-12-27 13:21:50'),
        updateTime: null,
      },
      {
        id: 26,
        parentId: 0,
        type: 'M',
        name: '系统监控',
        path: 'monitor',
        icon: 'monitor',
        component: null,
        perms: '',
        hidden: 0,
        disable: false,
        orderNum: 5,
        createTime: new Date('2022-12-27 13:23:29'),
        updateTime: new Date('2023-01-03 18:47:27'),
      },
      {
        id: 27,
        parentId: 26,
        type: 'C',
        name: '定时任务',
        path: 'task',
        icon: 'job',
        component: '/monitor/task/index',
        perms: 'monitor:task:list',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2022-12-27 13:26:29'),
        updateTime: new Date('2023-01-01 21:08:35'),
      },
      {
        id: 28,
        parentId: 27,
        type: 'B',
        name: '添加任务',
        path: null,
        icon: null,
        component: null,
        perms: 'monitor:task:add',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2022-12-27 13:32:42'),
        updateTime: null,
      },
      {
        id: 29,
        parentId: 27,
        type: 'B',
        name: '修改任务',
        path: null,
        icon: null,
        component: null,
        perms: 'monitor:task:update',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2022-12-27 13:33:45'),
        updateTime: null,
      },
      {
        id: 30,
        parentId: 27,
        type: 'B',
        name: '删除任务',
        path: null,
        icon: null,
        component: null,
        perms: 'monitor:task:delete',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2022-12-27 13:34:29'),
        updateTime: null,
      },
      {
        id: 31,
        parentId: 27,
        type: 'B',
        name: '修改任务状态',
        path: null,
        icon: null,
        component: null,
        perms: 'monitor:task:status',
        hidden: 0,
        disable: false,
        orderNum: 4,
        createTime: new Date('2022-12-27 13:43:24'),
        updateTime: null,
      },
      {
        id: 32,
        parentId: 27,
        type: 'B',
        name: '运行任务',
        path: null,
        icon: null,
        component: null,
        perms: 'monitor:task:run',
        hidden: 0,
        disable: false,
        orderNum: 5,
        createTime: new Date('2022-12-27 13:45:34'),
        updateTime: null,
      },
      {
        id: 33,
        parentId: 13,
        type: 'B',
        name: '修改角色状态',
        path: null,
        icon: null,
        component: null,
        perms: 'system:role:status',
        hidden: 0,
        disable: false,
        orderNum: 4,
        createTime: new Date('2022-12-27 13:46:39'),
        updateTime: null,
      },
      {
        id: 34,
        parentId: 0,
        type: 'M',
        name: '网站管理',
        path: 'web',
        icon: 'international',
        component: null,
        perms: '',
        hidden: 0,
        disable: false,
        orderNum: 6,
        createTime: new Date('2022-12-30 17:22:33'),
        updateTime: new Date('2023-02-14 09:46:29'),
      },
      {
        id: 35,
        parentId: 34,
        type: 'C',
        name: '友链管理',
        path: 'friend',
        icon: 'friend',
        component: '/web/friend/index',
        perms: 'web:friend:list',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2022-12-30 17:33:15'),
        updateTime: null,
      },
      {
        id: 36,
        parentId: 0,
        type: 'M',
        name: '消息管理',
        path: 'news',
        icon: 'email',
        component: null,
        perms: '',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2022-12-30 17:50:06'),
        updateTime: new Date('2022-12-30 18:02:12'),
      },
      {
        id: 37,
        parentId: 36,
        type: 'C',
        name: '留言管理',
        path: 'message',
        icon: 'form',
        component: '/news/message/index',
        perms: 'news:message:list',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2022-12-30 17:58:25'),
        updateTime: new Date('2022-12-30 18:01:47'),
      },
      {
        id: 38,
        parentId: 36,
        type: 'C',
        name: '评论管理',
        path: 'comment',
        icon: 'comment',
        component: '/news/comment/index',
        perms: 'news:comment:list',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2022-12-30 17:59:37'),
        updateTime: new Date('2022-12-30 18:03:35'),
      },
      {
        id: 39,
        parentId: 35,
        type: 'B',
        name: '添加友链',
        path: null,
        icon: null,
        component: null,
        perms: 'web:friend:add',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2022-12-30 18:56:22'),
        updateTime: null,
      },
      {
        id: 40,
        parentId: 35,
        type: 'B',
        name: '删除友链',
        path: null,
        icon: null,
        component: null,
        perms: 'web:friend:delete',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2022-12-30 18:56:42'),
        updateTime: null,
      },
      {
        id: 41,
        parentId: 35,
        type: 'B',
        name: '修改友链',
        path: null,
        icon: null,
        component: null,
        perms: 'web:friend:update',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2022-12-30 18:57:08'),
        updateTime: null,
      },
      {
        id: 42,
        parentId: 37,
        type: 'B',
        name: '删除留言',
        path: null,
        icon: null,
        component: null,
        perms: 'news:message:delete',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2022-12-30 22:05:53'),
        updateTime: null,
      },
      {
        id: 45,
        parentId: 37,
        type: 'B',
        name: '审核留言',
        path: null,
        icon: null,
        component: null,
        perms: 'news:message:pass',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2022-12-30 22:29:24'),
        updateTime: null,
      },
      {
        id: 46,
        parentId: 34,
        type: 'C',
        name: '网站配置',
        path: 'site',
        icon: 'example',
        component: '/web/site/index',
        perms: 'web:site:list',
        hidden: 0,
        disable: false,
        orderNum: 5,
        createTime: new Date('2022-12-31 11:50:45'),
        updateTime: new Date('2023-01-03 18:49:17'),
      },
      {
        id: 51,
        parentId: 34,
        type: 'C',
        name: '相册管理',
        path: 'album',
        icon: 'album',
        component: '/web/album/index',
        perms: 'web:album:list',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2023-01-01 18:16:40'),
        updateTime: new Date('2023-01-03 18:49:06'),
      },
      {
        id: 52,
        parentId: 34,
        type: 'C',
        name: '照片管理',
        path: 'photo/:albumId',
        icon: 'photo',
        component: '/web/photo/index',
        perms: 'web:photo:list',
        hidden: 1,
        disable: false,
        orderNum: 4,
        createTime: new Date('2023-01-01 18:18:11'),
        updateTime: new Date('2023-01-01 18:39:22'),
      },
      {
        id: 53,
        parentId: 26,
        type: 'C',
        name: '在线用户',
        path: 'online',
        icon: 'online',
        component: '/monitor/online/index',
        perms: 'monitor:online:list',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2023-01-01 21:07:48'),
        updateTime: new Date('2023-01-01 21:08:29'),
      },
      {
        id: 54,
        parentId: 51,
        type: 'B',
        name: '添加相册',
        path: null,
        icon: null,
        component: null,
        perms: 'web:album:add',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2023-01-02 19:01:33'),
        updateTime: null,
      },
      {
        id: 55,
        parentId: 51,
        type: 'B',
        name: '删除相册',
        path: null,
        icon: null,
        component: null,
        perms: 'web:album:delete',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2023-01-02 19:02:03'),
        updateTime: null,
      },
      {
        id: 56,
        parentId: 51,
        type: 'B',
        name: '修改相册',
        path: null,
        icon: null,
        component: null,
        perms: 'web:album:update',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2023-01-02 19:02:50'),
        updateTime: null,
      },
      {
        id: 57,
        parentId: 51,
        type: 'B',
        name: '编辑相册',
        path: null,
        icon: null,
        component: null,
        perms: 'web:album:edit',
        hidden: 0,
        disable: false,
        orderNum: 4,
        createTime: new Date('2023-01-02 19:03:40'),
        updateTime: null,
      },
      {
        id: 58,
        parentId: 51,
        type: 'B',
        name: '上传相册封面',
        path: null,
        icon: null,
        component: null,
        perms: 'web:album:upload',
        hidden: 0,
        disable: false,
        orderNum: 5,
        createTime: new Date('2023-01-02 19:04:38'),
        updateTime: null,
      },
      {
        id: 60,
        parentId: 12,
        type: 'B',
        name: '编辑菜单',
        path: null,
        icon: null,
        component: null,
        perms: 'system:menu:edit',
        hidden: 0,
        disable: false,
        orderNum: 4,
        createTime: new Date('2023-01-03 18:29:57'),
        updateTime: null,
      },
      {
        id: 61,
        parentId: 34,
        type: 'C',
        name: '说说管理',
        path: 'talk',
        icon: 'talk',
        component: '/web/talk/index',
        perms: 'web:talk:list',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2023-01-03 18:48:28'),
        updateTime: new Date('2023-01-03 18:48:41'),
      },
      {
        id: 62,
        parentId: 61,
        type: 'B',
        name: '添加说说',
        path: null,
        icon: null,
        component: null,
        perms: 'web:talk:add',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2023-01-05 19:16:42'),
        updateTime: null,
      },
      {
        id: 63,
        parentId: 61,
        type: 'B',
        name: '删除说说',
        path: null,
        icon: null,
        component: null,
        perms: 'web:talk:delete',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2023-01-05 19:17:07'),
        updateTime: null,
      },
      {
        id: 64,
        parentId: 61,
        type: 'B',
        name: '修改说说',
        path: null,
        icon: null,
        component: null,
        perms: 'web:talk:update',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2023-01-05 19:17:36'),
        updateTime: null,
      },
      {
        id: 65,
        parentId: 61,
        type: 'B',
        name: '编辑说说',
        path: null,
        icon: null,
        component: null,
        perms: 'web:talk:edit',
        hidden: 0,
        disable: false,
        orderNum: 4,
        createTime: new Date('2023-01-05 19:18:27'),
        updateTime: null,
      },
      {
        id: 66,
        parentId: 61,
        type: 'B',
        name: '上传说说图片',
        path: null,
        icon: null,
        component: null,
        perms: 'web:talk:upload',
        hidden: 0,
        disable: false,
        orderNum: 5,
        createTime: new Date('2023-01-05 19:18:52'),
        updateTime: null,
      },
      {
        id: 67,
        parentId: 46,
        type: 'B',
        name: '修改网站配置',
        path: null,
        icon: null,
        component: null,
        perms: 'web:site:update',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2023-01-08 09:15:56'),
        updateTime: null,
      },
      {
        id: 68,
        parentId: 46,
        type: 'B',
        name: '上传网站配置图片',
        path: null,
        icon: null,
        component: null,
        perms: 'web:site:upload',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2023-01-08 14:53:16'),
        updateTime: null,
      },
      {
        id: 69,
        parentId: 14,
        type: 'B',
        name: '修改用户',
        path: null,
        icon: null,
        component: null,
        perms: 'system:user:update',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2023-01-09 17:03:18'),
        updateTime: null,
      },
      {
        id: 70,
        parentId: 14,
        type: 'B',
        name: '修改用户状态',
        path: null,
        icon: null,
        component: null,
        perms: 'system:user:status',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2023-01-09 17:03:51'),
        updateTime: null,
      },
      {
        id: 71,
        parentId: 53,
        type: 'B',
        name: '下线用户',
        path: null,
        icon: null,
        component: null,
        perms: 'monitor:online:kick',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2023-01-09 19:18:33'),
        updateTime: null,
      },
      {
        id: 73,
        parentId: 1,
        type: 'C',
        name: '文章列表',
        path: 'list',
        icon: 'chart',
        component: '/blog/article/list',
        perms: 'blog:article:list',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2023-01-10 17:37:29'),
        updateTime: new Date('2023-02-21 15:36:09'),
      },
      {
        id: 76,
        parentId: 52,
        type: 'B',
        name: '添加照片',
        path: null,
        icon: null,
        component: null,
        perms: 'web:photo:add',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2023-01-11 18:45:28'),
        updateTime: null,
      },
      {
        id: 77,
        parentId: 52,
        type: 'B',
        name: '删除照片',
        path: null,
        icon: null,
        component: null,
        perms: 'web:photo:delete',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2023-01-11 18:45:51'),
        updateTime: null,
      },
      {
        id: 78,
        parentId: 52,
        type: 'B',
        name: '修改照片',
        path: null,
        icon: null,
        component: null,
        perms: 'web:photo:update',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2023-01-11 18:46:12'),
        updateTime: null,
      },
      {
        id: 79,
        parentId: 52,
        type: 'B',
        name: '上传照片',
        path: null,
        icon: null,
        component: null,
        perms: 'web:photo:upload',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2023-01-11 18:46:48'),
        updateTime: null,
      },
      {
        id: 80,
        parentId: 73,
        type: 'B',
        name: '添加文章',
        path: null,
        icon: null,
        component: null,
        perms: 'blog:article:add',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2023-01-14 15:25:29'),
        updateTime: null,
      },
      {
        id: 81,
        parentId: 73,
        type: 'B',
        name: '物理删除文章',
        path: null,
        icon: null,
        component: null,
        perms: 'blog:article:delete',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2023-01-14 15:26:44'),
        updateTime: null,
      },
      {
        id: 82,
        parentId: 73,
        type: 'B',
        name: '逻辑删除文章',
        path: null,
        icon: null,
        component: null,
        perms: 'blog:article:recycle',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2023-01-14 15:28:32'),
        updateTime: null,
      },
      {
        id: 83,
        parentId: 73,
        type: 'B',
        name: '更新文章',
        path: null,
        icon: null,
        component: null,
        perms: 'blog:article:update',
        hidden: 0,
        disable: false,
        orderNum: 4,
        createTime: new Date('2023-01-14 15:30:11'),
        updateTime: null,
      },
      {
        id: 84,
        parentId: 73,
        type: 'B',
        name: '编辑文章',
        path: null,
        icon: null,
        component: null,
        perms: 'blog:article:edit',
        hidden: 0,
        disable: false,
        orderNum: 5,
        createTime: new Date('2023-01-14 15:32:34'),
        updateTime: new Date('2023-01-14 15:32:54'),
      },
      {
        id: 85,
        parentId: 73,
        type: 'B',
        name: '上传文章图片',
        path: null,
        icon: null,
        component: null,
        perms: 'blog:article:upload',
        hidden: 0,
        disable: false,
        orderNum: 6,
        createTime: new Date('2023-01-14 15:34:05'),
        updateTime: new Date('2023-01-15 11:19:13'),
      },
      {
        id: 86,
        parentId: 73,
        type: 'B',
        name: '置顶文章',
        path: null,
        icon: null,
        component: null,
        perms: 'blog:article:top',
        hidden: 0,
        disable: false,
        orderNum: 7,
        createTime: new Date('2023-01-14 15:35:33'),
        updateTime: null,
      },
      {
        id: 87,
        parentId: 73,
        type: 'B',
        name: '推荐文章',
        path: null,
        icon: null,
        component: null,
        perms: 'blog:article:recommend',
        hidden: 0,
        disable: false,
        orderNum: 8,
        createTime: new Date('2023-01-14 15:36:08'),
        updateTime: null,
      },
      {
        id: 88,
        parentId: 73,
        type: 'B',
        name: '点赞文章',
        path: null,
        icon: null,
        component: null,
        perms: 'blog:article:like',
        hidden: 0,
        disable: false,
        orderNum: 9,
        createTime: new Date('2023-01-14 15:36:39'),
        updateTime: null,
      },
      {
        id: 93,
        parentId: 21,
        type: 'C',
        name: '访问日志',
        path: 'visit',
        icon: 'logininfor',
        component: '/system/log/visit',
        perms: 'log:visit:list',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2023-01-28 19:04:09'),
        updateTime: new Date('2023-01-28 19:06:52'),
      },
      {
        id: 94,
        parentId: 93,
        type: 'B',
        name: '删除访问日志',
        path: null,
        icon: null,
        component: null,
        perms: 'log:visit:delete',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2023-01-28 19:05:31'),
        updateTime: null,
      },
      {
        id: 95,
        parentId: 14,
        type: 'B',
        name: '修改用户邮箱',
        path: null,
        icon: null,
        component: null,
        perms: 'user:email:update',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2023-01-31 09:26:22'),
        updateTime: null,
      },
      {
        id: 96,
        parentId: 14,
        type: 'B',
        name: '修改用户头像',
        path: null,
        icon: null,
        component: null,
        perms: 'user:avatar:update',
        hidden: 0,
        disable: false,
        orderNum: 4,
        createTime: new Date('2023-01-31 09:27:03'),
        updateTime: null,
      },
      {
        id: 97,
        parentId: 14,
        type: 'B',
        name: '修改用户信息',
        path: null,
        icon: null,
        component: null,
        perms: 'user:info:update',
        hidden: 0,
        disable: false,
        orderNum: 5,
        createTime: new Date('2023-01-31 09:27:37'),
        updateTime: null,
      },
      {
        id: 98,
        parentId: 14,
        type: 'B',
        name: '修改用户密码',
        path: null,
        icon: null,
        component: null,
        perms: 'user:password:update',
        hidden: 0,
        disable: false,
        orderNum: 6,
        createTime: new Date('2023-01-31 09:28:10'),
        updateTime: null,
      },
      {
        id: 99,
        parentId: 38,
        type: 'B',
        name: '添加评论',
        path: null,
        icon: null,
        component: null,
        perms: 'news:comment:add',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2023-02-08 19:09:25'),
        updateTime: null,
      },
      {
        id: 100,
        parentId: 38,
        type: 'B',
        name: '删除评论',
        path: null,
        icon: null,
        component: null,
        perms: 'news:comment:delete',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2023-02-08 19:09:57'),
        updateTime: null,
      },
      {
        id: 101,
        parentId: 38,
        type: 'B',
        name: '审核评论',
        path: null,
        icon: null,
        component: null,
        perms: 'news:comment:pass',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2023-02-08 19:10:26'),
        updateTime: null,
      },
      {
        id: 102,
        parentId: 38,
        type: 'B',
        name: '点赞评论',
        path: null,
        icon: null,
        component: null,
        perms: 'news:comment:like',
        hidden: 0,
        disable: false,
        orderNum: 4,
        createTime: new Date('2023-02-08 19:10:45'),
        updateTime: null,
      },
      {
        id: 103,
        parentId: 61,
        type: 'B',
        name: '点赞说说',
        path: null,
        icon: null,
        component: null,
        perms: 'web:talk:like',
        hidden: 0,
        disable: false,
        orderNum: 6,
        createTime: new Date('2023-02-10 11:16:23'),
        updateTime: null,
      },
      {
        id: 104,
        parentId: 21,
        type: 'C',
        name: '任务日志',
        path: 'task',
        icon: 'job',
        component: '/system/log/task',
        perms: 'log:task:list',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2023-02-14 10:28:28'),
        updateTime: new Date('2023-02-14 10:28:41'),
      },
      {
        id: 105,
        parentId: 104,
        type: 'B',
        name: '删除任务日志',
        path: null,
        icon: null,
        component: null,
        perms: 'log:task:delete',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2023-02-14 11:21:06'),
        updateTime: null,
      },
      {
        id: 106,
        parentId: 104,
        type: 'B',
        name: '清空任务日志',
        path: null,
        icon: null,
        component: null,
        perms: 'log:task:clear',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2023-02-14 11:21:28'),
        updateTime: null,
      },
      {
        id: 108,
        parentId: 1,
        type: 'C',
        name: '发布文章',
        path: 'write',
        icon: 'edit',
        component: '/blog/article/write',
        perms: 'blog:article:list',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2023-02-21 13:32:22'),
        updateTime: new Date('2023-02-21 15:36:04'),
      },
      {
        id: 111,
        parentId: 1,
        type: 'C',
        name: '修改文章',
        path: 'write/:articleId',
        icon: 'edit',
        component: '/blog/article/write',
        perms: 'blog:article:list',
        hidden: 1,
        disable: false,
        orderNum: 5,
        createTime: new Date('2023-02-21 15:40:11'),
        updateTime: new Date('2023-02-21 15:41:07'),
      },
      {
        id: 123,
        parentId: 11,
        type: 'C',
        name: '文件管理',
        path: 'file',
        icon: 'file',
        component: '/system/file/index',
        perms: 'system:file:list',
        hidden: 0,
        disable: false,
        orderNum: 4,
        createTime: new Date('2023-03-09 10:57:29'),
        updateTime: null,
      },
      {
        id: 124,
        parentId: 123,
        type: 'B',
        name: '上传文件',
        path: null,
        icon: null,
        component: null,
        perms: 'system:file:upload',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2023-03-10 23:11:33'),
        updateTime: null,
      },
      {
        id: 125,
        parentId: 123,
        type: 'B',
        name: '新建文件夹',
        path: null,
        icon: null,
        component: null,
        perms: 'system:file:createFolder',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2023-03-10 23:12:11'),
        updateTime: null,
      },
      {
        id: 126,
        parentId: 123,
        type: 'B',
        name: '删除文件',
        path: null,
        icon: null,
        component: null,
        perms: 'system:file:delete',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2023-03-10 23:12:45'),
        updateTime: null,
      },
      {
        id: 127,
        parentId: 34,
        type: 'C',
        name: '轮播图',
        path: 'carousel',
        icon: 'carousel',
        component: '/web/carousel/index',
        perms: 'web:carousel:list',
        hidden: 0,
        disable: false,
        orderNum: 6,
        createTime: new Date('2024-10-17 15:21:28'),
        updateTime: null,
      },
      {
        id: 128,
        parentId: 127,
        type: 'B',
        name: '上传轮播图片',
        path: null,
        icon: null,
        component: null,
        perms: 'web:carousel:upload',
        hidden: 0,
        disable: false,
        orderNum: 1,
        createTime: new Date('2024-10-22 13:44:20'),
        updateTime: new Date('2024-10-22 13:44:50'),
      },
      {
        id: 129,
        parentId: 127,
        type: 'B',
        name: '添加轮播图',
        path: null,
        icon: null,
        component: null,
        perms: 'web:carousel:add',
        hidden: 0,
        disable: false,
        orderNum: 2,
        createTime: new Date('2024-10-22 13:45:04'),
        updateTime: null,
      },
      {
        id: 130,
        parentId: 127,
        type: 'B',
        name: '修改轮播图',
        path: null,
        icon: null,
        component: null,
        perms: 'web:carousel:update',
        hidden: 0,
        disable: false,
        orderNum: 3,
        createTime: new Date('2024-10-22 13:45:17'),
        updateTime: new Date('2024-10-22 13:45:22'),
      },
      {
        id: 131,
        parentId: 127,
        type: 'B',
        name: '删除轮播图',
        path: null,
        icon: null,
        component: null,
        perms: 'web:carousel:delete',
        hidden: 0,
        disable: false,
        orderNum: 4,
        createTime: new Date('2024-10-22 13:45:38'),
        updateTime: null,
      },
      {
        id: 132,
        parentId: 127,
        type: 'B',
        name: '修改轮播图状态',
        path: null,
        icon: null,
        component: null,
        perms: 'web:carousel:status',
        hidden: 0,
        disable: false,
        orderNum: 5,
        createTime: new Date('2024-10-22 13:45:54'),
        updateTime: null,
      },
      {
        id: 133,
        parentId: 11,
        type: 'C',
        name: '系统接口',
        path: 'api',
        icon: 'swagger',
        component: '/system/swagger/index',
        perms: '',
        hidden: 0,
        disable: false,
        orderNum: 5,
        createTime: new Date('2024-11-04 11:02:29'),
        updateTime: new Date('2024-11-04 11:02:58'),
      },
    ];

    // 创建和保存所有菜单
    for (const menu of menuData) {
      const newMenu = menuRepository.create(menu);
      await menuRepository.save(newMenu);
    }

    logger.log(`成功初始化了 ${menuData.length} 条菜单数据`);
  } catch (error) {
    logger.error('初始化菜单数据失败: ' + error.message);
    throw error;
  }
}
